services:
  app:
    image: hojas/fe-stack:latest
    container_name: fe-stack-app
    ports:
      - 127.0.0.1:5000:5000
    environment:
      PORT: 5000
      LETSENCRYPT_HOST: www.chenyuanxiang.com
      VIRTUAL_HOST: www.chenyuanxiang.com
      VIRTUAL_PORT: 5000
      VIRTUAL_PATH: /fe-stack

networks:
  default:
    name: nx_blog
    external: true
