services:
  app:
    image: hojas/fe-stack:latest
    container_name: fe-stack-app
    ports:
      - 127.0.0.1:3000:3000
    environment:
      LETSENCRYPT_HOST: www.chenyuanxiang.com
      VIRTUAL_HOST: www.chenyuanxiang.com
      VIRTUAL_PORT: 3000
      VIRTUAL_PATH: /
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    networks:
      - fe_stack
  acme-companion:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL=cyxhuan9@163.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    networks:
      - fe_stack

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  fe_stack:
    name: fe_stack
    driver: bridge
